version: "3.9"

services:
  app:
    container_name: prakticum-app
    image: prakticum-app
    build:
        context: .
        dockerfile: Dockerfile.app
        args:
          SERVER_PORT: ${SERVER_PORT}
          CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - ${SERVER_PORT}:3001
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    network_mode: bridge
    links:
      - 'postgres'

  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    network_mode: bridge
    restart: unless-stopped
  
volumes:
    postgres: